[package]
name = "macindecode-ac4-player"
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
publish = false

[dependencies]
eframe = { version = "=0.36.1", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "wayland",
    "wgpu",
    "x11",
] }
macindecode-ac4-inspect = { git = "https://github.com/SakuzyPeng/MacinDecode-AC4-Core.git", rev = "eb7c6132072daad3b4312bd23c2d9e8a63fa1265" }
rfd = { version = "=0.17.2", default-features = false, features = [
    "common-controls-v6",
    "wayland",
    "xdg-portal",
] }
serde_json = "1"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"

[profile.release]
codegen-units = 1
lto = "thin"
strip = "debuginfo"
