//! The built-in demo track: Pachelbel's Canon in D, synthesised in real time.
//!
//! The player ships no audio. This module holds a *score* — note onsets,
//! durations and pitches — from which the synthesiser builds Scene blocks on
//! demand, so the demo costs no bytes on disk and raises no question about a
//! recording's rights.
//!
//! The piece is a deliberate choice rather than a convenient one. An original
//! cue would be cheaper to write, but nobody could tell a renderer's mistake
//! from an unfamiliar phrase: a dropped voice, a delayed submission or a
//! mirrored position would all just sound like the piece. In a canon everyone
//! knows, the second voice plays what the first played eight beats ago, so the
//! listener is holding the correct answer while the wrong one arrives.
//!
//! Two structural facts do most of the work here, and both come from the piece:
//!
//! - **It is a canon**, so [`score::CANON_LINE`] is stored once and the three
//!   violins are that line at [`score::CANON_ENTRIES`]. A voice cannot drift
//!   from its companions, because there is nothing to drift from — and a
//!   spatial arrangement that gives each voice the same path at the same offset
//!   makes the canon visible as well as audible.
//! - **It is built over a ground bass**, two bars repeated twenty-eight times.
//!   The ground carries the harmony throughout, so fading, silencing or
//!   deactivating any subset of the voices above it still sounds correct —
//!   which is what lets the demo switch what it is demonstrating without the
//!   music going wrong. That two-bar period is also the demo's phase unit.
//!
//! The score is generated by `scripts/generate-demo-score.py` from the Mutopia
//! `LilyPond` sources and committed, so neither the build nor the tests reach the
//! network. The generator checks every bar against its four beats and every
//! ground statement against the ostinato; this module's tests then re-derive
//! the object budget independently and require the two to agree.

#[cfg(any(feature = "decode", test))]
use crate::decoder::DecodedSceneBlock;

pub(crate) mod score;
// The synthesiser builds Scene blocks, whose constructors exist only where
// there is a decoder to have produced one. The score above is plain data and
// stays available to every build, including the inspection-only shell.
#[cfg(any(feature = "decode", test))]
pub(crate) mod stage;
#[cfg(any(feature = "decode", test))]
pub(crate) mod voice;

/// One note: when it starts, how long it is held, and which pitch it sounds.
///
/// Ticks are [`score::TICKS_PER_BEAT`] to the quarter and always relative to
/// the start of whichever table the note belongs to, so a table can be placed
/// anywhere on the timeline without rewriting it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct Note {
    onset: u32,
    duration: u32,
    pitch: u8,
}

pub(crate) const fn note(onset: u32, duration: u32, pitch: u8) -> Note {
    Note {
        onset,
        duration,
        pitch,
    }
}

impl Note {
    pub(crate) const fn onset(self) -> u32 {
        self.onset
    }

    #[cfg_attr(
        not(test),
        allow(
            dead_code,
            reason = "these express the contract the score is generated against -- the \
                      phase budget, the note geometry, the golden digest -- and the \
                      tests are what check it; the arrangement reads the tables directly"
        )
    )]
    pub(crate) const fn duration(self) -> u32 {
        self.duration
    }

    /// MIDI note number; 69 is A4.
    pub(crate) const fn pitch(self) -> u8 {
        self.pitch
    }

    #[cfg_attr(
        not(test),
        allow(
            dead_code,
            reason = "these express the contract the score is generated against -- the \
                      phase budget, the note geometry, the golden digest -- and the \
                      tests are what check it; the arrangement reads the tables directly"
        )
    )]
    pub(crate) const fn end(self) -> u32 {
        self.onset.saturating_add(self.duration)
    }
}

/// One stretch of the demo, and what it spends to demonstrate what it does.
///
/// Phases exist because the object budget is scarce and the demonstrations are
/// not simultaneous. Rather than hold every object the whole programme could
/// ever want, the demo reuses a fixed set of element IDs over time: the IDs
/// never change, so [`crate::decoder::SceneSignature`] stays constant and no
/// phase boundary can force a stream rebuild.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct Phase {
    name: &'static str,
    first_statement: u32,
    last_statement: u32,
    pool_slots: u32,
    per_note: bool,
    peak_ringing: u32,
}

pub(crate) const fn phase(
    name: &'static str,
    first_statement: u32,
    last_statement: u32,
    pool_slots: u32,
    per_note: bool,
    peak_ringing: u32,
) -> Phase {
    Phase {
        name,
        first_statement,
        last_statement,
        pool_slots,
        per_note,
        peak_ringing,
    }
}

impl Phase {
    pub(crate) const fn name(self) -> &'static str {
        self.name
    }

    /// Inclusive ground-statement range, counting from one.
    #[cfg_attr(
        not(test),
        allow(
            dead_code,
            reason = "these express the contract the score is generated against -- the \
                      phase budget, the note geometry, the golden digest -- and the \
                      tests are what check it; the arrangement reads the tables directly"
        )
    )]
    pub(crate) const fn statements(self) -> (u32, u32) {
        (self.first_statement, self.last_statement)
    }

    /// Ticks from the first bar: the half-open span this phase occupies.
    pub(crate) const fn span(self) -> (u32, u32) {
        (
            (self.first_statement - 1) * score::TICKS_PER_STATEMENT,
            self.last_statement * score::TICKS_PER_STATEMENT,
        )
    }

    /// Slots this phase may hand out beyond the musical spine.
    pub(crate) const fn pool_slots(self) -> u32 {
        self.pool_slots
    }

    /// Whether the phase gives each ringing note an object of its own.
    ///
    /// Only such a phase is bounded by the pool: everywhere else an object
    /// holds an instrument, and a phrase costs no more than a single note.
    pub(crate) const fn per_note(self) -> bool {
        self.per_note
    }

    /// Notes the generator measured as ringing together at this phase's peak.
    #[cfg_attr(
        not(test),
        allow(
            dead_code,
            reason = "these express the contract the score is generated against -- the \
                      phase budget, the note geometry, the golden digest -- and the \
                      tests are what check it; the arrangement reads the tables directly"
        )
    )]
    pub(crate) const fn peak_ringing(self) -> u32 {
        self.peak_ringing
    }

    /// Slots held at once: the spine, less the canon voices a per-note phase
    /// has already emptied into the pool, plus the pool itself.
    #[cfg_attr(
        not(test),
        allow(
            dead_code,
            reason = "these express the contract the score is generated against -- the \
                      phase budget, the note geometry, the golden digest -- and the \
                      tests are what check it; the arrangement reads the tables directly"
        )
    )]
    pub(crate) const fn objects_held(self) -> u32 {
        let spine = if self.per_note {
            score::SPINE_SLOTS - score::CANON_VOICE_SLOTS
        } else {
            score::SPINE_SLOTS
        };
        spine + self.pool_slots
    }
}

/// The demo track, ready to answer any block on its timeline.
///
/// Construction does all the arranging; [`Self::block_at`] only reads. That
/// split is what makes a block a pure function of its start frame, and it is
/// the reason a seek is nothing more than a different argument: there is no
/// state to rewind, no tail to re-render and no index to build.
#[cfg(any(feature = "decode", test))]
pub(crate) struct DemoProgram {
    sample_rate: u32,
    timbres: Vec<voice::Timbre>,
    /// Every note, indexed by the slot that sounds it and sorted by onset.
    by_slot: Vec<Vec<stage::Placement>>,
    lfe: Vec<(i64, u8)>,
    duration_frames: u64,
}

/// Position updates a moving object publishes inside one full block.
///
/// Windows takes one position per object per render quantum, so an in-block
/// update quantises to the next boundary there while the `MacinRender` producer
/// submits it as given. Publishing several per block is what makes that
/// difference visible instead of theoretical.
#[cfg(any(feature = "decode", test))]
const UPDATES_PER_BLOCK: u32 = 4;

#[cfg(any(feature = "decode", test))]
impl DemoProgram {
    pub(crate) fn new(sample_rate: u32) -> Self {
        let timbres = stage::timbres();
        let arrangement = stage::arrange(sample_rate, &timbres);
        let mut by_slot = vec![Vec::new(); stage::SLOTS];
        for placement in arrangement.placements {
            by_slot[placement.slot].push(placement);
        }
        for slot in &mut by_slot {
            slot.sort_by_key(|placement| placement.onset);
        }
        Self {
            sample_rate,
            timbres,
            by_slot,
            lfe: stage::lfe_onsets(sample_rate),
            duration_frames: arrangement.duration_frames,
        }
    }

    pub(crate) const fn sample_rate(&self) -> u32 {
        self.sample_rate
    }

    pub(crate) const fn duration_frames(&self) -> u64 {
        self.duration_frames
    }

    /// Frames still to come after `start_frame`, capped at one block.
    pub(crate) fn block_frames_at(&self, start_frame: i64) -> u32 {
        let remaining = self
            .duration_frames
            .saturating_sub(u64::try_from(start_frame.max(0)).unwrap_or(u64::MAX));
        u32::try_from(remaining)
            .unwrap_or(u32::MAX)
            .min(stage::BLOCK_FRAMES)
    }

    /// One Scene block, built from the timeline alone.
    pub(crate) fn block_at(&self, start_frame: i64) -> DecodedSceneBlock {
        let frames = self.block_frames_at(start_frame);
        let end = start_frame + i64::from(frames);
        let length = frames as usize;
        let mut objects = Vec::with_capacity(stage::SLOTS);
        let mut updates = Vec::new();

        for slot in 0..stage::SLOTS {
            let mut samples = vec![0.0f32; length];
            for placement in &self.by_slot[slot] {
                if placement.release <= start_frame || placement.onset >= end {
                    continue;
                }
                voice::render(
                    &mut samples,
                    &self.timbres[placement.timbre],
                    voice::frequency_of(placement.pitch),
                    placement.level,
                    placement.onset - start_frame,
                    placement.release - start_frame,
                    self.sample_rate,
                );
            }
            let initial = self.slot_metadata(slot, start_frame, end, &mut updates);
            objects.push(stage::object(slot, initial, samples));
        }

        let mut bed = vec![0.0f32; length];
        for &(onset, pitch) in &self.lfe {
            if onset >= end {
                break;
            }
            voice::render(
                &mut bed,
                &self.timbres[stage::timbre::TIMPANI],
                voice::frequency_of(pitch),
                0.2,
                onset - start_frame,
                i64::MAX,
                self.sample_rate,
            );
        }

        updates.sort_by_key(|update| (update.offset_frames(), update.element_id()));
        stage::block(
            self.sample_rate,
            start_frame,
            frames,
            objects,
            Some(stage::lfe(stage::bed_state(), bed)),
            updates,
        )
    }

    /// Each block carries its actual starting gain and the remaining ramp.
    /// Computing both from the arrangement makes arbitrary seeks agree with
    /// continuous playback, without any mutable metadata history.
    fn slot_metadata(
        &self,
        slot: usize,
        start: i64,
        end: i64,
        updates: &mut Vec<crate::decoder::SceneMetadataUpdate>,
    ) -> crate::decoder::SpatialObjectState {
        use crate::decoder::{FIELD_GAIN, FIELD_POSITION, SceneMetadataUpdate};

        let mut initial = stage::idle_state();
        let placements = &self.by_slot[slot];
        let element = stage::element_id(slot);
        for (index, placement) in placements.iter().enumerate() {
            let next_onset = placements
                .get(index + 1)
                .map_or(i64::MAX, |next| next.onset);
            // The newest note owns the metadata even while its predecessor's
            // damped PCM tail is still mixed into the same instrument.
            let until = placement.release.min(next_onset).min(end);
            let from = placement.onset.max(start);
            if from >= until {
                continue;
            }
            let offset = u32::try_from(from - start).unwrap_or(0);
            let state = placement.state_at(from, self.sample_rate);
            if from == start {
                initial = state;
            } else {
                updates.push(stage::update(element, offset, 0, state));
            }
            let gain_end = placement.onset + i64::from(placement.ramp_frames);
            if gain_end > from {
                updates.push(SceneMetadataUpdate::new(
                    element,
                    offset,
                    u32::try_from(gain_end - from).unwrap_or(0),
                    FIELD_GAIN,
                    placement.state_at(gain_end, self.sample_rate),
                ));
            }
            if matches!(placement.motion, stage::Motion::Orbit { .. }) {
                let step = i64::from(stage::BLOCK_FRAMES / UPDATES_PER_BLOCK);
                let mut frame = from;
                while frame < until {
                    let target = ((frame / step + 1) * step).min(until);
                    updates.push(SceneMetadataUpdate::new(
                        element,
                        u32::try_from(frame - start).unwrap_or(0),
                        u32::try_from(target - frame).unwrap_or(0),
                        FIELD_POSITION,
                        placement.state_at(target, self.sample_rate),
                    ));
                    frame = target;
                }
            }
            if placement.release == until && until < next_onset && until < end {
                updates.push(stage::update(
                    element,
                    u32::try_from(until - start).unwrap_or(0),
                    0,
                    stage::idle_state(),
                ));
            }
        }
        initial
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::decoder::{SceneLfePcm, SceneObjectPcm, SpatialObjectState};

    const TICKS_PER_BAR: u32 = score::TICKS_PER_BEAT * score::BEATS_PER_BAR;

    const RATE: u32 = 48_000;

    #[test]
    fn demo_gain_ramps_continue_across_blocks() {
        let programme = programme();
        let placement = programme.by_slot[8]
            .iter()
            .find(|p| {
                p.ramp_frames > 0 && p.gain < 1.0 && p.onset % i64::from(stage::BLOCK_FRAMES) != 0
            })
            .expect("a falling gain ramp");
        let start = placement.onset - placement.onset % i64::from(stage::BLOCK_FRAMES);
        let first = programme.block_at(start);
        let second = programme.block_at(start + i64::from(stage::BLOCK_FRAMES));
        let left = &first.objects()[8];
        let right = &second.objects()[8];
        let before = crate::decoder::metadata::element_state_at(
            &first,
            left.element_id(),
            left.initial_state(),
            stage::BLOCK_FRAMES,
        )
        .unwrap()
        .linear_gain()
        .unwrap();
        let after = crate::decoder::metadata::element_state_at(
            &second,
            right.element_id(),
            right.initial_state(),
            0,
        )
        .unwrap()
        .linear_gain()
        .unwrap();
        assert!(
            (before - after).abs() < 1e-4,
            "gain jumped from {before} to {after} at frame {} during a {}-frame ramp",
            second.start_frame(),
            placement.ramp_frames
        );
    }

    fn programme() -> DemoProgram {
        DemoProgram::new(RATE)
    }

    #[test]
    fn seeking_into_a_gain_ramp_matches_continuous_playback() {
        let programme = programme();
        for slot in [8, 9] {
            for placement in programme.by_slot[slot].iter().filter(|p| p.ramp_frames > 0) {
                // Includes unfinished ramps interrupted by the next note.
                for elapsed in [0, 1, 1024, 6000, 11_999] {
                    let frame = placement.onset + elapsed;
                    let base = frame - frame % i64::from(stage::BLOCK_FRAMES);
                    let continuous = programme.block_at(base);
                    let seeked = programme.block_at(frame);
                    let object = &continuous.objects()[slot];
                    let expected = crate::decoder::metadata::element_state_at(
                        &continuous,
                        object.element_id(),
                        object.initial_state(),
                        u32::try_from(frame - base).unwrap(),
                    )
                    .unwrap();
                    let actual = seeked.objects()[slot].initial_state().unwrap();
                    assert_eq!(actual.metadata_active(), expected.metadata_active());
                    assert!(
                        (actual.linear_gain().unwrap() - expected.linear_gain().unwrap()).abs()
                            < 1e-5,
                        "seek changed slot {slot}'s gain at frame {frame}"
                    );
                }
            }
        }
    }

    /// Blocks worth looking at: the first and last of every phase, plus a walk
    /// across each one. Rendering all 4 450 blocks of the programme is the
    /// ignored sweep below; these cover every transition it could hide.
    fn sampled_starts(programme: &DemoProgram) -> Vec<i64> {
        let mut starts = vec![0];
        for phase in score::PHASES {
            let (first, last) = phase.span();
            let start = stage::frame_of(u64::from(first), RATE);
            let end = stage::frame_of(u64::from(last), RATE);
            let step = ((end - start) / 6).max(i64::from(stage::BLOCK_FRAMES));
            let mut frame = start;
            while frame < end {
                starts.push(frame - frame % i64::from(stage::BLOCK_FRAMES));
                frame += step;
            }
        }
        let last = i64::try_from(programme.duration_frames()).expect("a bounded programme");
        starts.push(last - last % i64::from(stage::BLOCK_FRAMES));
        starts.retain(|&start| start >= 0 && start < last);
        starts.sort_unstable();
        starts.dedup();
        starts
    }

    fn peak_of(block: &crate::decoder::DecodedSceneBlock) -> f32 {
        block
            .objects()
            .iter()
            .flat_map(SceneObjectPcm::samples)
            .chain(block.lfe().into_iter().flat_map(SceneLfePcm::samples))
            .fold(0.0f32, |peak, sample| peak.max(sample.abs()))
    }

    #[test]
    fn the_whole_programme_holds_one_scene_signature() {
        // Sixteen slots exist from the first block to the last, so no phase
        // boundary can look like a topology change and force a rebuild.
        let programme = programme();
        let mut signature = None;
        for start in sampled_starts(&programme) {
            let block = programme.block_at(start);
            assert_eq!(block.objects().len(), stage::SLOTS);
            assert!(block.lfe().is_some(), "the bed must be present throughout");
            let current = crate::decoder::SceneSignature::from_block(&block);
            match &signature {
                None => signature = Some(current),
                Some(expected) => {
                    assert_eq!(&current, expected, "the signature changed at frame {start}");
                }
            }
        }
        assert!(signature.is_some(), "the programme produced no blocks");
    }

    #[test]
    fn the_scene_stays_inside_the_object_budget() {
        let programme = programme();
        let block = programme.block_at(0);
        assert!(
            u32::try_from(block.objects().len()).expect("a small scene")
                <= score::MAX_DYNAMIC_OBJECTS,
            "the demo must configure on an endpoint offering sixteen objects"
        );
    }

    #[test]
    fn a_block_depends_on_nothing_but_its_start_frame() {
        // The property seeking rests on. Two programmes that have rendered
        // different histories must still answer the same block identically.
        let played = programme();
        let seeked = programme();
        let starts = sampled_starts(&played);
        for &start in &starts {
            let _ = played.block_at(start);
        }
        let probe = starts[starts.len() / 2];
        let after_playing = played.block_at(probe);
        let after_seeking = seeked.block_at(probe);
        for (left, right) in after_playing.objects().iter().zip(after_seeking.objects()) {
            assert_eq!(left.element_id(), right.element_id());
            assert_eq!(left.samples(), right.samples(), "a seek changed the audio");
        }
        assert_eq!(
            after_playing.metadata_updates(),
            after_seeking.metadata_updates()
        );
    }

    #[test]
    fn nothing_clips_and_the_programme_keeps_its_headroom() {
        let programme = programme();
        let mut worst = 0.0f32;
        for start in sampled_starts(&programme) {
            let block = programme.block_at(start);
            for object in block.objects() {
                assert!(
                    object.samples().iter().all(|sample| sample.is_finite()),
                    "a non-finite sample at frame {start}"
                );
            }
            worst = worst.max(peak_of(&block));
        }
        assert!(worst < 1.0, "an object clipped at {worst}");
        // -6 dBFS of summed headroom, so the renderer is not handed a signal
        // that only survives because nothing happened to line up.
        assert!(
            worst < 0.5,
            "the programme peaks at {worst}, over its budget"
        );
    }

    #[test]
    fn every_metadata_update_declares_what_changed() {
        // The MacinRender ABI rejects an empty changed-field mask, and a
        // consumer that received one could not tell an update from a no-op.
        let programme = programme();
        for start in sampled_starts(&programme) {
            for update in programme.block_at(start).metadata_updates() {
                assert_ne!(update.changed_fields(), 0, "an empty mask at frame {start}");
                assert!(
                    update.offset_frames() < stage::BLOCK_FRAMES,
                    "an update past the end of its block"
                );
            }
        }
    }

    #[test]
    fn blocks_tile_the_timeline_without_gap_or_overlap() {
        // Walked by arithmetic alone: rendering all 4 400 blocks is the ignored
        // sweep below, and a gap would be a gap whether or not it held audio.
        let programme = programme();
        let mut frame = 0i64;
        let mut blocks = 0u32;
        while programme.block_frames_at(frame) > 0 {
            frame += i64::from(programme.block_frames_at(frame));
            blocks += 1;
            assert!(blocks < 100_000, "the timeline did not terminate");
        }
        assert_eq!(
            u64::try_from(frame).expect("a bounded programme"),
            programme.duration_frames(),
            "the blocks must reach the end exactly"
        );
        for start in sampled_starts(&programme) {
            let block = programme.block_at(start);
            assert_eq!(block.start_frame(), start);
            assert_eq!(block.duration_frames(), programme.block_frames_at(start));
            for object in block.objects() {
                assert_eq!(object.samples().len(), block.duration_frames() as usize);
            }
        }
    }

    #[test]
    fn a_pool_slot_is_silent_before_it_is_handed_to_another_note() {
        // The failure the keyboard phase would otherwise put on display: a
        // decaying note dragged to the position of the note that replaced it.
        let timbres = stage::timbres();
        let arrangement = stage::arrange(RATE, &timbres);
        let keyboard = score::PHASES
            .iter()
            .find(|phase| phase.per_note())
            .expect("a per-note phase");
        let (first, last) = keyboard.span();
        let span = stage::frame_of(u64::from(first), RATE)..stage::frame_of(u64::from(last), RATE);
        let mut previous: Vec<Option<(i64, [f32; 3])>> = vec![None; stage::SLOTS];
        let mut checked = 0;
        for placement in &arrangement.placements {
            if !span.contains(&placement.onset) {
                continue;
            }
            let here = placement.motion.at(0.0);
            if let Some((release, there)) = previous[placement.slot]
                && there.iter().zip(here).any(|(a, b)| (a - b).abs() > 1e-6)
            {
                assert!(
                    placement.onset >= release,
                    "slot {} was moved while frame {release} was still ringing",
                    placement.slot
                );
                checked += 1;
            }
            previous[placement.slot] = Some((placement.release, here));
        }
        assert!(checked > 100, "only {checked} handovers were examined");
    }

    #[test]
    fn the_arrangement_never_takes_a_slot_back_from_a_ringing_note() {
        // The safety valve exists so the sixteen-object cap holds whatever the
        // score says; this asserts the shipped programme never needs it. If a
        // tempo, a decay or a phase boundary changes, this goes red before a
        // listener hears a tail cut off.
        let timbres = stage::timbres();
        assert_eq!(
            stage::arrange(RATE, &timbres).stolen,
            0,
            "a pool slot was reclaimed early; move the phase, shorten the decay \
             or widen the pool rather than raising the cap"
        );
    }

    #[test]
    fn the_keyboard_lays_its_keys_out_like_a_keyboard() {
        // This was wrong once, and no test noticed: the sharps were placed
        // nearer the listener than the naturals, which is the opposite of an
        // instrument and turns the mapping into a scale with a wobble in it.
        // Reading the manual against the code found it; this keeps it found.
        let timbres = stage::timbres();
        let arrangement = stage::arrange(RATE, &timbres);
        let keyboard = score::PHASES
            .iter()
            .find(|phase| phase.per_note())
            .expect("a per-note phase");
        let (first, last) = keyboard.span();
        let span = stage::frame_of(u64::from(first), RATE)..stage::frame_of(u64::from(last), RATE);

        let mut keys: Vec<(u8, [f32; 3])> = arrangement
            .placements
            .iter()
            // The ground and the continuo keep their own places through this
            // phase; only the pool's notes are laid out as keys.
            .filter(|placement| {
                span.contains(&placement.onset) && placement.timbre == stage::timbre::HARPSICHORD
            })
            .map(|placement| (placement.pitch, placement.motion.at(0.0)))
            .collect();
        keys.sort_by_key(|&(pitch, _)| pitch);
        keys.dedup_by_key(|&mut (pitch, _)| pitch);
        assert!(keys.len() > 12, "only {} distinct keys", keys.len());

        for pair in keys.windows(2) {
            assert!(
                pair[1].1[0] > pair[0].1[0],
                "MIDI {} must sit right of {}",
                pair[1].0,
                pair[0].0
            );
        }
        let sharp = |pitch: u8| matches!(pitch % 12, 1 | 3 | 6 | 8 | 10);
        let naturals = keys.iter().filter(|(pitch, _)| !sharp(*pitch));
        let sharps = keys.iter().filter(|(pitch, _)| sharp(*pitch));
        let nearest_natural = naturals
            .map(|(_, position)| position[1])
            .fold(f32::MIN, f32::max);
        let furthest_sharp = sharps
            .map(|(_, position)| position[1])
            .fold(f32::MAX, f32::min);
        assert!(
            furthest_sharp > nearest_natural,
            "every sharp must sit further forward than every natural: \
             sharps from {furthest_sharp}, naturals to {nearest_natural}"
        );
    }

    #[test]
    fn the_reference_phase_pairs_a_head_locked_twin_with_a_scene_relative_one() {
        let timbres = stage::timbres();
        let arrangement = stage::arrange(RATE, &timbres);
        let phase = score::PHASES
            .iter()
            .find(|phase| phase.name() == "reference")
            .expect("a reference phase");
        let (first, last) = phase.span();
        let span = stage::frame_of(u64::from(first), RATE)..stage::frame_of(u64::from(last), RATE);
        let twins: Vec<_> = arrangement
            .placements
            .iter()
            .filter(|placement| span.contains(&placement.onset) && placement.slot >= stage::SPINE)
            .collect();
        let locked = twins
            .iter()
            .filter(|placement| placement.tracking.head_locked())
            .count();
        assert!(locked > 0, "no head-locked object in the reference phase");
        assert_eq!(
            locked * 2,
            twins.len(),
            "the comparison needs one of each, playing the same material"
        );
        // Same timbre and same pitches: the reference frame is the only
        // variable, which is the whole point of the comparison.
        assert!(
            twins
                .windows(2)
                .all(|pair| pair[0].timbre == pair[1].timbre)
        );
    }

    #[test]
    fn a_silent_object_still_declares_its_gain() {
        // What keeps the gain ring on the floor while the cube recedes: an
        // object persistently silent by content, not by volume.
        let timbres = stage::timbres();
        let arrangement = stage::arrange(RATE, &timbres);
        let mute: Vec<_> = arrangement
            .placements
            .iter()
            .filter(|placement| placement.level == 0.0)
            .collect();
        assert!(!mute.is_empty(), "the gain-ring phase placed nothing");
        assert!(
            mute.iter().all(|placement| placement.gain > 0.0),
            "a silent object must still ask for its gain"
        );
        assert!(
            mute.iter().all(|placement| placement.metadata_active),
            "and must still be active, or there is nothing to draw"
        );
    }

    /// Fold the demo down to a stereo WAV so a person can hear it.
    ///
    /// The tests above can say the arithmetic is right, that nothing clips and
    /// that the signature never moves. None of them can say it sounds like
    /// Pachelbel -- which is the entire reason a familiar piece was chosen, and
    /// the one check that has to be done by ear.
    ///
    /// This is a listening aid, not a renderer: objects are panned by their `x`
    /// alone, so it says nothing about elevation, head tracking or what either
    /// real output path does with the same Scene.
    ///
    /// ```text
    /// MACINDECODE_DEMO_WAV=/tmp/demo.wav cargo test \
    ///     decoder::demo::tests::folds_the_demo_down_for_listening -- --ignored
    /// ```
    #[test]
    #[ignore = "writes a WAV for listening; needs MACINDECODE_DEMO_WAV"]
    #[allow(
        clippy::cast_possible_truncation,
        clippy::cast_precision_loss,
        reason = "a listening aid: samples are clamped to [-1, 1] before scaling \
                  into i16, and the excerpt is bounded to seconds of audio"
    )]
    fn folds_the_demo_down_for_listening() {
        let Ok(path) = std::env::var("MACINDECODE_DEMO_WAV") else {
            eprintln!("set MACINDECODE_DEMO_WAV to a path to write the excerpt");
            return;
        };
        let seconds = |name: &str, fallback: f64| {
            std::env::var(name)
                .ok()
                .and_then(|value| value.parse::<f64>().ok())
                .unwrap_or(fallback)
        };
        let programme = programme();
        let rate = f64::from(RATE);
        let start = (seconds("MACINDECODE_DEMO_WAV_START", 0.0) * rate) as i64;
        let wanted = (seconds("MACINDECODE_DEMO_WAV_SECONDS", 30.0) * rate) as i64;

        let mut stereo: Vec<i16> = Vec::new();
        let mut frame = start - start % i64::from(stage::BLOCK_FRAMES);
        while frame < start + wanted && programme.block_frames_at(frame) > 0 {
            let block = programme.block_at(frame);
            let length = block.duration_frames() as usize;
            let mut left = vec![0.0f32; length];
            let mut right = vec![0.0f32; length];
            for object in block.objects() {
                // Constant power from the object's declared `x`, taken once per
                // block: enough to tell the voices apart, and no more.
                let across = object
                    .initial_state()
                    .and_then(SpatialObjectState::position)
                    .map_or(0.0, |position| position.x().clamp(-1.0, 1.0));
                let gain = object
                    .initial_state()
                    .and_then(SpatialObjectState::linear_gain)
                    .unwrap_or(1.0);
                let active = object
                    .initial_state()
                    .is_some_and(SpatialObjectState::metadata_active);
                if !active {
                    continue;
                }
                let (gl, gr) = (
                    f32::midpoint(1.0, -across).sqrt() * gain,
                    f32::midpoint(1.0, across).sqrt() * gain,
                );
                for (index, sample) in object.samples().iter().enumerate() {
                    left[index] += sample * gl;
                    right[index] += sample * gr;
                }
            }
            if let Some(bed) = block.lfe() {
                for (index, sample) in bed.samples().iter().enumerate() {
                    left[index] += sample * 0.7;
                    right[index] += sample * 0.7;
                }
            }
            for (l, r) in left.into_iter().zip(right) {
                stereo.push((l.clamp(-1.0, 1.0) * f32::from(i16::MAX)) as i16);
                stereo.push((r.clamp(-1.0, 1.0) * f32::from(i16::MAX)) as i16);
            }
            frame += i64::from(block.duration_frames());
        }

        let bytes = u32::try_from(stereo.len() * 2).expect("a bounded excerpt");
        let mut wav = Vec::with_capacity(stereo.len() * 2 + 44);
        wav.extend_from_slice(b"RIFF");
        wav.extend_from_slice(&(36 + bytes).to_le_bytes());
        wav.extend_from_slice(b"WAVEfmt ");
        wav.extend_from_slice(&16u32.to_le_bytes());
        wav.extend_from_slice(&1u16.to_le_bytes());
        wav.extend_from_slice(&2u16.to_le_bytes());
        wav.extend_from_slice(&RATE.to_le_bytes());
        wav.extend_from_slice(&(RATE * 4).to_le_bytes());
        wav.extend_from_slice(&4u16.to_le_bytes());
        wav.extend_from_slice(&16u16.to_le_bytes());
        wav.extend_from_slice(b"data");
        wav.extend_from_slice(&bytes.to_le_bytes());
        for sample in stereo {
            wav.extend_from_slice(&sample.to_le_bytes());
        }
        std::fs::write(&path, wav).expect("the excerpt could be written");
        eprintln!("wrote {path}");
    }

    /// Render every block of the programme end to end.
    ///
    /// Ignored for cost, not for dependencies: it needs no media, no device and
    /// no GPU, just the six seconds a debug build takes to synthesise three
    /// minutes of audio. That ratio is itself worth knowing -- the decode
    /// worker has to stay ahead of playback, and thirty times over is the
    /// margin it does it by.
    #[test]
    #[ignore = "renders the whole programme; about six seconds in a debug build"]
    fn the_whole_programme_renders_within_its_headroom() {
        let programme = programme();
        let mut frame = 0i64;
        let mut worst = 0.0f32;
        while programme.block_frames_at(frame) > 0 {
            let block = programme.block_at(frame);
            assert_eq!(block.start_frame(), frame);
            for object in block.objects() {
                assert_eq!(object.samples().len(), block.duration_frames() as usize);
                assert!(object.samples().iter().all(|sample| sample.is_finite()));
            }
            worst = worst.max(peak_of(&block));
            frame += i64::from(block.duration_frames());
        }
        assert!(worst < 0.5, "the programme peaks at {worst}");
    }

    /// Every violin onset in ticks from the first bar, across all three voices.
    fn violin_onsets() -> Vec<u32> {
        let mut onsets = Vec::new();
        for (voice, tail) in score::CANON_TAILS.iter().enumerate() {
            let entry = score::CANON_ENTRIES[voice];
            onsets.extend(score::CANON_LINE.iter().map(|note| entry + note.onset()));
            let after = entry + score::CANON_LINE_TICKS;
            onsets.extend(tail.iter().map(|note| after + note.onset()));
        }
        onsets.sort_unstable();
        onsets
    }

    /// How long a pool slot must be left alone before it is handed on.
    fn guard_ticks() -> f64 {
        f64::from(score::STEAL_GUARD_TAUS)
            * f64::from(score::KEYBOARD_TAU_SECONDS)
            * f64::from(score::TICKS_PER_BEAT)
            * f64::from(score::TEMPO_BPM)
            / 60.0
    }

    /// The most notes still inside the guard window at any onset in the span.
    ///
    /// Derived here from the note tables rather than read from the phase table,
    /// so the generator's arithmetic and this one have to agree.
    fn peak_ringing(onsets: &[u32], span: (u32, u32)) -> u32 {
        let guard = guard_ticks();
        let mut peak = 0;
        let mut start = 0;
        for (index, &onset) in onsets.iter().enumerate() {
            if onset < span.0 || onset >= span.1 {
                continue;
            }
            while f64::from(onsets[start]) <= f64::from(onset) - guard {
                start += 1;
            }
            peak = peak.max(u32::try_from(index - start + 1).expect("a bounded window"));
        }
        peak
    }

    #[test]
    fn the_canon_delay_equals_the_ground_period() {
        // Why any subset of the voices still sounds right: each voice enters
        // exactly one ground statement after the last, so all three meet the
        // ostinato at the same point in its harmony.
        for pair in score::CANON_ENTRIES.windows(2) {
            assert_eq!(
                pair[1] - pair[0],
                score::TICKS_PER_STATEMENT,
                "the canon delay must be one ground statement"
            );
        }
        assert_eq!(score::CANON_ENTRIES[0], score::TICKS_PER_STATEMENT);
    }

    #[test]
    fn the_ground_and_its_coda_fill_the_piece() {
        assert_eq!(
            score::GROUND.last().expect("a ground statement").end(),
            score::TICKS_PER_STATEMENT,
            "the ostinato must fill its two bars exactly, or it cannot repeat"
        );
        let repeated = score::GROUND_REPEATS * score::TICKS_PER_STATEMENT;
        let coda = score::GROUND_CODA.last().expect("a closing bar").end();
        assert_eq!(
            repeated + coda.max(TICKS_PER_BAR),
            score::BARS * TICKS_PER_BAR
        );
    }

    #[test]
    fn each_violin_spans_the_whole_piece() {
        for (voice, tail) in score::CANON_TAILS.iter().enumerate() {
            let entry = score::CANON_ENTRIES[voice];
            let last = tail.last().map_or(score::CANON_LINE_TICKS, |note| {
                score::CANON_LINE_TICKS + note.end()
            });
            let end = entry + last;
            assert!(
                end <= score::BARS * TICKS_PER_BAR,
                "violin {} runs past the final bar",
                voice + 1
            );
            assert!(
                end > (score::BARS - 1) * TICKS_PER_BAR,
                "violin {} stops before the final bar",
                voice + 1
            );
        }
    }

    #[test]
    fn a_voice_never_overlaps_itself() {
        for (name, notes) in std::iter::once(("canon line", score::CANON_LINE))
            .chain(score::CANON_TAILS.iter().enumerate().map(|(voice, tail)| {
                (
                    ["violin one tail", "violin two tail", "violin three tail"][voice],
                    *tail,
                )
            }))
            .chain(std::iter::once(("ground", score::GROUND)))
        {
            for pair in notes.windows(2) {
                assert!(
                    pair[0].end() <= pair[1].onset(),
                    "{name}: a note at {} outlives the next onset at {}",
                    pair[0].onset(),
                    pair[1].onset()
                );
            }
        }
    }

    #[test]
    fn the_phases_tile_the_ground_statements() {
        let mut expected = 1;
        for phase in score::PHASES {
            let (first, last) = phase.statements();
            assert_eq!(first, expected, "a gap or overlap before {}", phase.name());
            assert!(last >= first, "{} runs backwards", phase.name());
            expected = last + 1;
        }
        assert_eq!(
            expected - 1,
            score::GROUND_REPEATS,
            "the phases must cover every ground statement"
        );
    }

    #[test]
    fn no_phase_holds_more_objects_than_the_budget_allows() {
        for phase in score::PHASES {
            assert!(
                phase.objects_held() <= score::MAX_DYNAMIC_OBJECTS,
                "{} holds {} objects, over the cap of {}",
                phase.name(),
                phase.objects_held(),
                score::MAX_DYNAMIC_OBJECTS
            );
        }
    }

    #[test]
    fn a_per_note_phase_never_has_to_steal_a_slot() {
        // The whole demo rests on never truncating a tail it did not mean to.
        // If this fails, move the phase off the dense statements, shorten the
        // decay, or widen the pool -- do not raise the cap.
        for phase in score::PHASES.iter().filter(|phase| phase.per_note()) {
            assert!(
                phase.peak_ringing() <= phase.pool_slots(),
                "{} needs {} slots for its notes but holds {}",
                phase.name(),
                phase.peak_ringing(),
                phase.pool_slots()
            );
        }
    }

    #[test]
    fn the_object_peak_matches_what_the_generator_measured() {
        let onsets = violin_onsets();
        for phase in score::PHASES {
            assert_eq!(
                peak_ringing(&onsets, phase.span()),
                phase.peak_ringing(),
                "{} disagrees with the generator about how many notes ring together",
                phase.name()
            );
        }
    }

    #[test]
    fn every_note_still_hashes_to_the_transcribed_score() {
        // FNV-1a over every field of every note, in table order, mirroring
        // `scripts/generate-demo-score.py`. A wrong note inside the pitch set
        // the score already uses passes every other check here; this is what
        // stops one from reaching a listener who would certainly notice.
        let mut digest: u64 = 0xcbf2_9ce4_8422_2325;
        let tables = std::iter::once(score::CANON_LINE)
            .chain(score::CANON_TAILS)
            .chain([score::GROUND, score::GROUND_CODA]);
        for table in tables {
            for note in table {
                let mut payload = [0u8; 9];
                payload[..4].copy_from_slice(&note.onset().to_le_bytes());
                payload[4..8].copy_from_slice(&note.duration().to_le_bytes());
                payload[8] = note.pitch();
                for byte in payload {
                    digest = (digest ^ u64::from(byte)).wrapping_mul(0x100_0000_01b3);
                }
            }
        }
        assert_eq!(
            digest,
            score::SCORE_DIGEST,
            "the score changed; re-run scripts/generate-demo-score.py rather than editing it"
        );
    }

    #[test]
    fn the_score_uses_the_pitches_the_tables_claim() {
        let pitches = score::CANON_LINE
            .iter()
            .chain(score::GROUND)
            .chain(score::GROUND_CODA)
            .chain(score::CANON_TAILS.iter().flat_map(|tail| tail.iter()))
            .map(|note| note.pitch())
            .collect::<Vec<_>>();
        let mut classes = pitches.iter().map(|pitch| pitch % 12).collect::<Vec<_>>();
        classes.sort_unstable();
        classes.dedup();
        assert_eq!(classes, score::PITCH_CLASSES, "the accidentals changed");
        let low = *pitches.iter().min().expect("a scored pitch");
        let high = *pitches.iter().max().expect("a scored pitch");
        assert_eq!((low, high), score::PITCH_RANGE, "the range changed");
    }
}
