//! The built-in demo track: Pachelbel's Canon in D, synthesised in real time.
//!
//! The player ships no audio. This module holds a *score* — note onsets,
//! durations and pitches — from which the synthesiser builds Scene blocks on
//! demand, so the demo costs no bytes on disk and raises no question about a
//! recording's rights.
//!
//! The piece is a deliberate choice rather than a convenient one. An original
//! cue would be cheaper to write, but nobody could tell a renderer's mistake
//! from an unfamiliar phrase: a dropped voice, a delayed submission or a
//! mirrored position would all just sound like the piece. In a canon everyone
//! knows, the second voice plays what the first played eight beats ago, so the
//! listener is holding the correct answer while the wrong one arrives.
//!
//! Two structural facts do most of the work here, and both come from the piece:
//!
//! - **It is a canon**, so [`score::CANON_LINE`] is stored once and the three
//!   violins are that line at [`score::CANON_ENTRIES`]. A voice cannot drift
//!   from its companions, because there is nothing to drift from — and a
//!   spatial arrangement that gives each voice the same path at the same offset
//!   makes the canon visible as well as audible.
//! - **It is built over a ground bass**, two bars repeated twenty-eight times.
//!   The ground carries the harmony throughout, so fading, silencing or
//!   deactivating any subset of the voices above it still sounds correct —
//!   which is what lets the demo switch what it is demonstrating without the
//!   music going wrong. That two-bar period is also the demo's phase unit.
//!
//! The score is generated by `scripts/generate-demo-score.py` from the Mutopia
//! `LilyPond` sources and committed, so neither the build nor the tests reach the
//! network. The generator checks every bar against its four beats and every
//! ground statement against the ostinato; this module's tests then re-derive
//! the object budget independently and require the two to agree.

pub(crate) mod score;

/// One note: when it starts, how long it is held, and which pitch it sounds.
///
/// Ticks are [`score::TICKS_PER_BEAT`] to the quarter and always relative to
/// the start of whichever table the note belongs to, so a table can be placed
/// anywhere on the timeline without rewriting it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct Note {
    onset: u32,
    duration: u32,
    pitch: u8,
}

pub(crate) const fn note(onset: u32, duration: u32, pitch: u8) -> Note {
    Note {
        onset,
        duration,
        pitch,
    }
}

impl Note {
    pub(crate) const fn onset(self) -> u32 {
        self.onset
    }

    pub(crate) const fn duration(self) -> u32 {
        self.duration
    }

    /// MIDI note number; 69 is A4.
    pub(crate) const fn pitch(self) -> u8 {
        self.pitch
    }

    pub(crate) const fn end(self) -> u32 {
        self.onset.saturating_add(self.duration)
    }
}

/// One stretch of the demo, and what it spends to demonstrate what it does.
///
/// Phases exist because the object budget is scarce and the demonstrations are
/// not simultaneous. Rather than hold every object the whole programme could
/// ever want, the demo reuses a fixed set of element IDs over time: the IDs
/// never change, so [`crate::decoder::SceneSignature`] stays constant and no
/// phase boundary can force a stream rebuild.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct Phase {
    name: &'static str,
    first_statement: u32,
    last_statement: u32,
    pool_slots: u32,
    per_note: bool,
    peak_ringing: u32,
}

pub(crate) const fn phase(
    name: &'static str,
    first_statement: u32,
    last_statement: u32,
    pool_slots: u32,
    per_note: bool,
    peak_ringing: u32,
) -> Phase {
    Phase {
        name,
        first_statement,
        last_statement,
        pool_slots,
        per_note,
        peak_ringing,
    }
}

impl Phase {
    pub(crate) const fn name(self) -> &'static str {
        self.name
    }

    /// Inclusive ground-statement range, counting from one.
    pub(crate) const fn statements(self) -> (u32, u32) {
        (self.first_statement, self.last_statement)
    }

    /// Ticks from the first bar: the half-open span this phase occupies.
    pub(crate) const fn span(self) -> (u32, u32) {
        (
            (self.first_statement - 1) * score::TICKS_PER_STATEMENT,
            self.last_statement * score::TICKS_PER_STATEMENT,
        )
    }

    /// Slots this phase may hand out beyond the musical spine.
    pub(crate) const fn pool_slots(self) -> u32 {
        self.pool_slots
    }

    /// Whether the phase gives each ringing note an object of its own.
    ///
    /// Only such a phase is bounded by the pool: everywhere else an object
    /// holds an instrument, and a phrase costs no more than a single note.
    pub(crate) const fn per_note(self) -> bool {
        self.per_note
    }

    /// Notes the generator measured as ringing together at this phase's peak.
    pub(crate) const fn peak_ringing(self) -> u32 {
        self.peak_ringing
    }

    /// Slots held at once: the spine, less the canon voices a per-note phase
    /// has already emptied into the pool, plus the pool itself.
    pub(crate) const fn objects_held(self) -> u32 {
        let spine = if self.per_note {
            score::SPINE_SLOTS - score::CANON_VOICE_SLOTS
        } else {
            score::SPINE_SLOTS
        };
        spine + self.pool_slots
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TICKS_PER_BAR: u32 = score::TICKS_PER_BEAT * score::BEATS_PER_BAR;

    /// Every violin onset in ticks from the first bar, across all three voices.
    fn violin_onsets() -> Vec<u32> {
        let mut onsets = Vec::new();
        for (voice, tail) in score::CANON_TAILS.iter().enumerate() {
            let entry = score::CANON_ENTRIES[voice];
            onsets.extend(score::CANON_LINE.iter().map(|note| entry + note.onset()));
            let after = entry + score::CANON_LINE_TICKS;
            onsets.extend(tail.iter().map(|note| after + note.onset()));
        }
        onsets.sort_unstable();
        onsets
    }

    /// How long a pool slot must be left alone before it is handed on.
    fn guard_ticks() -> f64 {
        f64::from(score::STEAL_GUARD_TAUS)
            * f64::from(score::KEYBOARD_TAU_SECONDS)
            * f64::from(score::TICKS_PER_BEAT)
            * f64::from(score::TEMPO_BPM)
            / 60.0
    }

    /// The most notes still inside the guard window at any onset in the span.
    ///
    /// Derived here from the note tables rather than read from the phase table,
    /// so the generator's arithmetic and this one have to agree.
    fn peak_ringing(onsets: &[u32], span: (u32, u32)) -> u32 {
        let guard = guard_ticks();
        let mut peak = 0;
        let mut start = 0;
        for (index, &onset) in onsets.iter().enumerate() {
            if onset < span.0 || onset >= span.1 {
                continue;
            }
            while f64::from(onsets[start]) <= f64::from(onset) - guard {
                start += 1;
            }
            peak = peak.max(u32::try_from(index - start + 1).expect("a bounded window"));
        }
        peak
    }

    #[test]
    fn the_canon_delay_equals_the_ground_period() {
        // Why any subset of the voices still sounds right: each voice enters
        // exactly one ground statement after the last, so all three meet the
        // ostinato at the same point in its harmony.
        for pair in score::CANON_ENTRIES.windows(2) {
            assert_eq!(
                pair[1] - pair[0],
                score::TICKS_PER_STATEMENT,
                "the canon delay must be one ground statement"
            );
        }
        assert_eq!(score::CANON_ENTRIES[0], score::TICKS_PER_STATEMENT);
    }

    #[test]
    fn the_ground_and_its_coda_fill_the_piece() {
        assert_eq!(
            score::GROUND.last().expect("a ground statement").end(),
            score::TICKS_PER_STATEMENT,
            "the ostinato must fill its two bars exactly, or it cannot repeat"
        );
        let repeated = score::GROUND_REPEATS * score::TICKS_PER_STATEMENT;
        let coda = score::GROUND_CODA.last().expect("a closing bar").end();
        assert_eq!(
            repeated + coda.max(TICKS_PER_BAR),
            score::BARS * TICKS_PER_BAR
        );
    }

    #[test]
    fn each_violin_spans_the_whole_piece() {
        for (voice, tail) in score::CANON_TAILS.iter().enumerate() {
            let entry = score::CANON_ENTRIES[voice];
            let last = tail.last().map_or(score::CANON_LINE_TICKS, |note| {
                score::CANON_LINE_TICKS + note.end()
            });
            let end = entry + last;
            assert!(
                end <= score::BARS * TICKS_PER_BAR,
                "violin {} runs past the final bar",
                voice + 1
            );
            assert!(
                end > (score::BARS - 1) * TICKS_PER_BAR,
                "violin {} stops before the final bar",
                voice + 1
            );
        }
    }

    #[test]
    fn a_voice_never_overlaps_itself() {
        for (name, notes) in std::iter::once(("canon line", score::CANON_LINE))
            .chain(score::CANON_TAILS.iter().enumerate().map(|(voice, tail)| {
                (
                    ["violin one tail", "violin two tail", "violin three tail"][voice],
                    *tail,
                )
            }))
            .chain(std::iter::once(("ground", score::GROUND)))
        {
            for pair in notes.windows(2) {
                assert!(
                    pair[0].end() <= pair[1].onset(),
                    "{name}: a note at {} outlives the next onset at {}",
                    pair[0].onset(),
                    pair[1].onset()
                );
            }
        }
    }

    #[test]
    fn the_phases_tile_the_ground_statements() {
        let mut expected = 1;
        for phase in score::PHASES {
            let (first, last) = phase.statements();
            assert_eq!(first, expected, "a gap or overlap before {}", phase.name());
            assert!(last >= first, "{} runs backwards", phase.name());
            expected = last + 1;
        }
        assert_eq!(
            expected - 1,
            score::GROUND_REPEATS,
            "the phases must cover every ground statement"
        );
    }

    #[test]
    fn no_phase_holds_more_objects_than_the_budget_allows() {
        for phase in score::PHASES {
            assert!(
                phase.objects_held() <= score::MAX_DYNAMIC_OBJECTS,
                "{} holds {} objects, over the cap of {}",
                phase.name(),
                phase.objects_held(),
                score::MAX_DYNAMIC_OBJECTS
            );
        }
    }

    #[test]
    fn a_per_note_phase_never_has_to_steal_a_slot() {
        // The whole demo rests on never truncating a tail it did not mean to.
        // If this fails, move the phase off the dense statements, shorten the
        // decay, or widen the pool -- do not raise the cap.
        for phase in score::PHASES.iter().filter(|phase| phase.per_note()) {
            assert!(
                phase.peak_ringing() <= phase.pool_slots(),
                "{} needs {} slots for its notes but holds {}",
                phase.name(),
                phase.peak_ringing(),
                phase.pool_slots()
            );
        }
    }

    #[test]
    fn the_object_peak_matches_what_the_generator_measured() {
        let onsets = violin_onsets();
        for phase in score::PHASES {
            assert_eq!(
                peak_ringing(&onsets, phase.span()),
                phase.peak_ringing(),
                "{} disagrees with the generator about how many notes ring together",
                phase.name()
            );
        }
    }

    #[test]
    fn every_note_still_hashes_to_the_transcribed_score() {
        // FNV-1a over every field of every note, in table order, mirroring
        // `scripts/generate-demo-score.py`. A wrong note inside the pitch set
        // the score already uses passes every other check here; this is what
        // stops one from reaching a listener who would certainly notice.
        let mut digest: u64 = 0xcbf2_9ce4_8422_2325;
        let tables = std::iter::once(score::CANON_LINE)
            .chain(score::CANON_TAILS)
            .chain([score::GROUND, score::GROUND_CODA]);
        for table in tables {
            for note in table {
                let mut payload = [0u8; 9];
                payload[..4].copy_from_slice(&note.onset().to_le_bytes());
                payload[4..8].copy_from_slice(&note.duration().to_le_bytes());
                payload[8] = note.pitch();
                for byte in payload {
                    digest = (digest ^ u64::from(byte)).wrapping_mul(0x100_0000_01b3);
                }
            }
        }
        assert_eq!(
            digest,
            score::SCORE_DIGEST,
            "the score changed; re-run scripts/generate-demo-score.py rather than editing it"
        );
    }

    #[test]
    fn the_score_uses_the_pitches_the_tables_claim() {
        let pitches = score::CANON_LINE
            .iter()
            .chain(score::GROUND)
            .chain(score::GROUND_CODA)
            .chain(score::CANON_TAILS.iter().flat_map(|tail| tail.iter()))
            .map(|note| note.pitch())
            .collect::<Vec<_>>();
        let mut classes = pitches.iter().map(|pitch| pitch % 12).collect::<Vec<_>>();
        classes.sort_unstable();
        classes.dedup();
        assert_eq!(classes, score::PITCH_CLASSES, "the accidentals changed");
        let low = *pitches.iter().min().expect("a scored pitch");
        let high = *pitches.iter().max().expect("a scored pitch");
        assert_eq!((low, high), score::PITCH_RANGE, "the range changed");
    }
}
